### PR TITLE
Components dev improvements

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Improves workflow for Runestone js development with PreTeXt books.

Goes with https://github.com/PreTeXtBook/pretext/pull/2197

### CODE REVIEW

**Comment by bnmnetp** [comment]
The last time I merged anything here was in Tacoma.  Seems odd, but we might have to talk through them.

**Comment by ascholerChemeketa** [comment]
Updated to assume RS files will be in `PRETEXT_OUTPUT/_static` without a subdir.

**Comment by bnmnetp** [comment]
I'm trying this out.  I'm getting the files into the right directory but I'm still seeing
```
vendors-node_modules_handsontable_es_index_js-node_modules_handsontable_dist_handsontable_ful-dcc440.js
```
I was thinking that would be gone.  We are also missing the webpack_static_imports.xml file.  Only the json file is present.

Maybe another extra command

**Comment by ascholerChemeketa** [comment]
The only `vendors-node_modules_...` files that get renamed are the entry files (js and CSS). They are the ones that are directly loaded by the webpage and thus need steady names. So we get `prefix-runtime-libs.bundle.js` and `prefix-runtime-libs.css` instead of the possibly changing `vendor-node_modules_....` names for the entry file for the libs.

The other `vendors-node_modules_...` files are chunks that webpack will load from the entry points. Those do not need cleaned-up names - I'm pretty sure trying to rename them would require all kinds of fixes to the webpack chunk loading.

------

I don't think developers need to output `webpack_static_imports.xml` - that isn't currently part of the webpack workflow. It looks like you make that with a separate shell script. Taking that part up with you in discord...

**Comment by bnmnetp** [comment]
So we will need to assume that the pretext book **has** been built with the `webpack_static_imports.xml` once and then we can do our dev builds of the javascript knowing that the pages have the right references in them.

**Review by bnmnetp — APPROVED** [review]

**Pull request merged**
