### PR TITLE
Removing caption from non-runestone multiple-choice (attempt 2)

### PR DESCRIPTION
**Pull request by geoff-cox**
After testing the updated code, the previous PR #380 didn't completely remove the captions from the non-runestone interactives.  After digging into the code a bit more, I believe checking for the runestone services to suppress the caption should happen at the interactive object level. 

This PR, reverts the changes made to the `addCaption` method in `runestonebase.js` and updates the `MultipleChoice` constructor in `mchoice.js`. I figured I would start with just one interactive and see if this PR produces the desired result before submitting a PR for the rest of them.

Also, if I understand the `addCaption` method, it appears to just append a `<p>` element to the bottom of a `runestone-component-ready` `<div>` element, so it seems safe to skip the `addCaption` call completely if runestone services are not detected.

### CODE REVIEW

**Comment by bnmnetp** [comment]
It looked like all the previous PR was trying to do was to remove the unique identifier, not the entire caption.

If you are building a book that you are using without the runestone server you can test it yourself before submitting another PR. -- See the docs here... https://runestone-monorepo.readthedocs.io/en/latest/

To test your change you can run `poetry install --with=dev` from the top level of the rs folder.  Run `poetry shell` to start up a python virtual environment.  Then when you make changes to javascript you just run the the `build.py` script in the `projects/interactives` folder and then rebuild your book -- make sure `use_services` is set to false the the pavement.py file for your book.

**Comment by geoff-cox** [comment]
Great, thanks for the info, I was wondering if it was possible to test on my own.  I will check it out.

**Comment by geoff-cox** [comment]
@bnmnetp Thanks for the link to the documentation. I have a question, but please let me know there is a better place to ask. 

I started to set up my dev environment for runestone, but I ran into a snag when initializing the database.

Details
- I am running everything on Ubuntu 22.04 within a windows wsl2 environment (_this could very well be the source of the error and my first mistake_).
- I updated the .env file to point to my books dir.
- I am choosing to let docker handle postgresql. 
- The docker servers appear to have been built successfully (via build.py).
- The database seem to have been successfully created (output below).

```
 ✔ Network rs_default  Created 
 ✔ Container rs-db-1   Started
```
However, when I attempt to initialize the db via
`$ docker compose run rsmanage rsmanage --verbose initdb`
I get the following error message:
```
WARN[0000] The "POSTGRESQL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_USERNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_SERVER" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_LOGIN" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_SECRET" variable is not set. Defaulting to a blank string.
[+] Building 0.0s (0/0)                                                                                  docker:default
WARN[0000] Found orphan containers ([rs-db-1]) for this project. If you removed or renamed this service in your 
compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Building 0.0s (0/0)                                                                                  docker:default
INFO - 2023-11-21 23:34:19,728 - Settings - Error path is /usr/books/tickets
You may want to define the DC_DEV_DBURL environment variable
You may want to define the DC_DBURL environment variable
Using configuration: development
Using database: runestone_dev
RUNESTONE_PATH is /usr/src/app
BOOK_PATH is /usr/books
SERVER_CONFIG is development
WEB2PY_CONFIG is development
The database URL is configured as postgresql+asyncpg://runestone:runestone@db/runestone_dev
DBNAME is runestone_dev
Checking database connection
postgresql+asyncpg://runestone:runestone@db/runestone_dev
Database connection successful
You may want to define the DC_DEV_DBURL environment variable
You may want to define the DC_DBURL environment variable
Initializing the database
/usr/local/lib/python3.10/site-packages/pydantic/main.py:308: UserWarning: Pydantic serializer warnings:
  Expected `bool` but got `ColumnDefault` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
ERROR - 2023-11-21 23:34:22,100 - read_key - No Key file is found will default to settings.jwt_secret
Traceback (most recent call last):
  File "/usr/local/bin/rsmanage", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1157, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 204, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 199, in wrapper
    return await func(*args)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/usr/local/lib/python3.10/site-packages/rsptx/rsmanage/core.py", line 240, in initdb
    await _initdb(config)
  File "/usr/local/lib/python3.10/site-packages/rsptx/rsmanage/core.py", line 183, in _initdb
    await create_initial_courses_users()
  File "/usr/local/lib/python3.10/site-packages/rsptx/db/crud.py", line 912, in create_initial_courses_users
    await create_user(
  File "/usr/local/lib/python3.10/site-packages/rsptx/db/crud.py", line 615, in create_user
    new_user.password = str(crypt(user.password)[0])
  File "/usr/local/lib/python3.10/site-packages/pydal/validators.py", line 4276, in __str__
    if ":" in self.crypt.key:
TypeError: a bytes-like object is required, not 'str'
```
Any thoughts?  It's probably something obivous, but I am struggling to troubleshoot it.

**Comment by bnmnetp** [comment]
No, not totally obvious.  I got this same error myself a few days ago.   It has to do with the Pydantic module being annoying and more pedantic than before.  the `jwt_key` variable used to be str, but now it is a bytes.  Pydantic used to be happy to convert between the two, but no longer.

I fixed it and pushed a fix 4 days ago.  So you probably just need to update your fork.

**Pull request closed without merging**
