### PR TITLE
Pass args instead of null

### PR DESCRIPTION
**Pull request by DavidCooperWCU**
This pass through method wasn’t passing necessary args for methods that take arguments. Now it does.

### CODE REVIEW

**Comment by bnmnetp** [comment]
@DavidCooperWCU 

What issue or problems does this PR address?

@bhoffman0 could your or Kate take a look at this and let me know what you think?

**Comment by bhoffman0** [comment]
I'd like to get @kmcdonnell2 to look at it too, since it's her code.  This is discussed more here https://discord.com/channels/1013815439161315348/1283143831067295766/1283874612572065927.

**Comment by DavidCooperWCU** [comment]
> @DavidCooperWCU 
> 
> 
> 
> What issue or problems does this PR address?
> 

When trying to get method output for instance methods that take arguments, without this fix, the codetesthelper will fail because the arguments are not sent to the method that requires arguments.

**Comment by bnmnetp** [comment]
OK, this looks pretty innocuous, have you tested it ?  Hopefully @kmcdonnell2 can give it a quick spin.  Or maybe there is any easy way to test it on replit or something that is documented somewhere?

**Comment by DavidCooperWCU** [comment]
This is a working test case. Tested on JGrasp, which is why the test class file is not RunestoneTest.java

[WorkingExample.zip](https://github.com/user-attachments/files/17019640/WorkingExample.zip)

**Comment by kmcdonnell2** [comment]
Yes, I believe this change works. I was able to do a quick verification on Repl.it.
https://replit.com/@kmcdonnell2/testCode

**Comment by bnmnetp** [comment]
OK, I will merge, and this should be live with the next update to the site.  Saturday at the latest.

**Pull request merged**
