### PR TITLE
Compose profiles

### PR DESCRIPTION
**Pull request by bnmnetp**
This uses some of the newer features of docker compose to simplify our setup.

With this, a first time user would not need anything more than the docker-compose.yml and the default settings provided in sample.env

### CODE REVIEW

**Comment by bnmnetp** [comment]
TODO:

- [ ] Update the docs
- [ ] Add `nginx_dstart_dev` service with a `dev` profile once I merge #462

**Comment by bnmnetp** [comment]
@jaltekruse @pearcej @ascholerChemeketa 

This seems much cleaner to me **and** easier to set up a single environment variable `COMPOSE_PROFILES` which is default to basic in the sample.env file.

Any thoughts?

**Comment by pearcej** [comment]
Much easier!  Thanks @bnmnetp !

**Comment by ascholerChemeketa** [comment]
Makes sense to me!

**Pull request merged**
